# Generated by Django 4.2.8 on 2024-06-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img.jpg', upload_to='img/%Y', verbose_name='Зображення'),
            preserve_default=False,
        ),
    ]
